### ISSUE TITLE
The frequency axis of the VNA and the effective frequncy scanned have a linear offset

### ISSUE THREAD

**Issue by LorenzoMinutolo** [LorenzoMinutolo/GPU_SDR#4]
Depending on the chirpness of the scan the offset vary, We should update the python API frequency axis calculation to match the C++ code that generates the steps.

**Comment by LorenzoMinutolo** [comment]
With the https://github.com/LorenzoMinutolo/GPU_SDR/commit/b8a18c7c553bace92db22f3179ce4ca47c2eed05 commit the issue should be negligible

There still is a small constant offset of a few mHz in the starting frequency setup (rate/(2**32)) that should be negligible. Further testing is needed to confirm the issue is gone.
@mkid-caltech @WanduiAlbert In particular a comparison between two VNA acquisitions focused (5 MHz span) a resonator in which one is let-to-right and the other one is right-to-left and both are with 100k points would be revealing.

**Comment by mkid-caltech** [comment]
![debug_2](https://user-images.githubusercontent.com/21132161/65085159-38887480-d962-11e9-9387-4e2e28442f49.png)

**Comment by LorenzoMinutolo** [comment]
We did this test few minutes ago, the number of points was 45k. Now that I think abut it, it may inconclusive because of the noise present in the VNA scans. In order to definitively close the issue we need something cleaner: @mkid-caltech some more readout power? @WanduiAlbert can you perform the same test on a high-Q TKID device?

**Comment by LorenzoMinutolo** [comment]
This has been solved by recalculating the (in the right way this time) the frequency axis of the VNA file.
NOTE: the data you have in the VNA file is correct; reanalyzing the files will update the frequency axis.
